spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sms
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    spring:
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQLDialect